-- Create database and messages table
CREATE DATABASE IF NOT EXISTS chat_support CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE chat_support;
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  sender VARCHAR(191) NOT NULL,
  role VARCHAR(50) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
